version: '3.8'

services:
  backend_eevm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_eevm
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=tu_super_secret_key_development
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  backend_eevm_data: 