version: "3.8"
services:
  backend_eevm:
    build: .
    container_name: backend_eevm
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "4000:4000"
    depends_on:
      - mysql_eevm
    networks:
      - eevm

networks:
  eevm:
    driver: bridge

volumes:
  mysql_data:
