
services:
  backend_eevm:
    build: .
    container_name: backend_eevm
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - backend_eevm_data:/app/data
    networks:
      - eevm

networks:
  eevm:
    driver: bridge

volumes:
  backend_eevm_data: