version: '3'

services:
  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: unless-stopped
    ports:
      # Expone pgBouncer en el puerto 6432 (puedes cambiarlo)
      - "6432:6432"
    environment:
      # Configuraci贸n de conexi贸n a PostgreSQL
      - DB_HOST=eevm.marceloremeseiro.com
      - DB_PORT=55000
      - DB_USER=postgres
      - DB_PASSWORD=eevm1122
      # Configuraci贸n de pgBouncer
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      # Bases de datos a las que se puede conectar
      - DATABASES=dbEevm
    volumes:
      # Puedes montar un archivo de configuraci贸n personalizado si lo necesitas
      - ./pgbouncer:/etc/pgbouncer
    networks:
      - eevm

networks:
  eevm:
    driver: bridge 