version: '3.8'

services:
  backend_eevm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_eevm
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/eevm
      - JWT_SECRET=tu_super_secret_key_development
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db_eevm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eevm
    volumes:
      - backend_eevm_data:/var/lib/postgresql/data

volumes:
  backend_eevm_data: 