version: '3'
services:
  app:
    build:
      context: .
      target: build
    image: my-express-app
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_DATABASE=dbEevm
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PORT=3306
    networks:
      - my-network
    depends_on:
      - database
    ports:
      - "3000:3000"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbEevm
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: .
      target: runtime
    image: my-nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
